name: MacOS

on: 
  push:
    paths:
      - '*.pro'
      - '**'
      - '.github/workflows/macos.yml'
  pull_request:
    paths:
      - '*.pro'
      - '**'
      - '.github/workflows/macos.yml'
  workflow_dispatch: # Add this to enable the manual trigger

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        qt_ver: [5.15.2]
        qt_arch: [clang_64]

    env:
      targetName: OCAuxiliaryTools
      VERSION: Mac
      orgName: OCAT
      
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          cached: 'false'
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          
      - name: build macos
        run: |
          qmake
          make
          
      - name: package
        run: |
          # Copy dependencies
          cp -r Database bin/release/${targetName}.app/Contents/MacOS/Database
          chmod +x bin/release/${targetName}.app/Contents/MacOS/Database/mac/macserial
          chmod +x bin/release/${targetName}.app/Contents/MacOS/Database/mac/ocvalidate
          chmod +x bin/release/${targetName}.app/Contents/MacOS/Database/mac/ocpasswordgen
          chmod +x bin/release/${targetName}.app/Contents/MacOS/Database/mac/CreateVault/create_vault.sh
          chmod +x bin/release/${targetName}.app/Contents/MacOS/Database/mac/CreateVault/RsaTool
          chmod +x bin/release/${targetName}.app/Contents/MacOS/Database/mac/CreateVault/sign.command
          cp -f Info.plist bin/release/${targetName}.app/Contents/Info.plist
          cp -f Database/mac/aria2c bin/release/${targetName}.app/Contents/MacOS/aria2c
          chmod +x bin/release/${targetName}.app/Contents/MacOS/aria2c
          rm bin/release/${targetName}.app/Contents/MacOS/Database/mac/aria2c
          cp -R -p -f bin/release/${targetName}.app ${targetName}.app
          macdeployqt ${targetName}.app -qmldir=. -verbose=1 -dmg
          cp ${targetName}.dmg bin/release/${targetName}.dmg 
          
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.orgName }}_${{ env.VERSION }}
          path: bin/release/${{ env.targetName }}.dmg
          
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/release/${{ env.targetName }}.dmg
          asset_name: ${{ env.orgName }}_${{ env.VERSION }}.dmg
          tag: ${{ github.ref }}
          overwrite: true
